### ISSUE TITLE
Switch selectors

### ISSUE THREAD

**Issue by corviday** [pacificclimate/scip#19]
Currently the app is using selectors from [PCIC React Components](https://github.com/pacificclimate/pcic-react-components). @rod-glover suggests switching to vanilla React Select, as the PCIC React Components are based on React Select 2, and currently React Select is on version 5, so there are features we're missing.

**Comment by rod-glover** [comment]
I'm working on pulling out the cascading selectors logic and other useful functions from pcic-react-components, which has proved too arcane for easy use.
